### ISSUE TITLE
Filepicker demo files

### ISSUE THREAD

**Issue by njpatter** [OSC/bc_js_filepicker#176]
Could you post the files used to create the Demo gif?  I've followed the steps in the Readme file, but am not able to get any of it to show up.  Thanks!

**Comment by johrstrom** [comment]
So you've built and deployed it. I think at mimimum you need `data-filepicker: true` attached to the form.yml.

```yaml
form:
  - input_file
attributes:
  input_file:
    label: 'Input File'
    data-filepicker: true
```

You can see this repo for how we use it at OSC.

https://github.com/OSC/bc_osc_codeserver

specifically here

https://github.com/OSC/bc_osc_codeserver/blob/0f4b5b1ccc29991319053dd451598eff0e465fec/form.yml.erb#L29-L34
